name: Update Manifest

on:
  repository_dispatch:
    types: [update-manifest]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to update to'
        required: true
        type: string

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup PowerShell
        shell: pwsh
        run: |
          # Install Scoop for testing
          if (!(Get-Command scoop -ErrorAction SilentlyContinue)) {
            Invoke-RestMethod get.scoop.sh | Invoke-Expression
          }

      - name: Update manifest
        shell: pwsh
        run: |
          $version = "${{ github.event.inputs.version || github.event.client_payload.version }}"
          $manifestPath = "bucket/apkhub.json"
          
          if (Test-Path $manifestPath) {
            Write-Host "Updating manifest for version $version"
            
            # Use scoop checkver to update the manifest
            scoop install git
            scoop bucket add main
            scoop install checkver
            
            # Update the version in manifest
            scoop checkver apkhub -dir bucket -u
            
            # Commit changes if any
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            
            if (git diff --quiet) {
              Write-Host "No changes to commit"
            } else {
              git add $manifestPath
              git commit -m "Update apkhub to version $version"
              git push
            }
          } else {
            Write-Host "Manifest file not found: $manifestPath"
            exit 1
          }

      - name: Test installation
        shell: pwsh
        run: |
          # Test the updated manifest
          scoop bucket add local .
          scoop install local/apkhub
          apkhub version